### ISSUE TITLE
what ip to use 

### ISSUE THREAD

**Issue by yousifk95** [Deviper-Labs/Web-Proxy-PHP-Colab#1]
Sorry for my little knowledge , how can i know what ip to use in my pc after the jupyter start working

**Comment by Deviper-Labs** [comment]
No worries, The code was exactly user friendly so it put the URL into a file, but I just added new changes to the workbook so that it actually shows the URL at the very end. Try it and tell me if it works!

**Comment by yousifk95** [comment]
thank you for your response , is still see an error >>>> AttributeError
Traceback (most recent call last)

<ipython-input-8-bb1110b1d18b> <https://localhost:8080/#> in <cell
line: 27>()     25 # Regex to find URL     26
---> 27 url = re.search("tcp.*$", data).group()     28      29 # Turn
tcp to http


AttributeError: 'NoneType' object has no attribute 'group'


‫في الاثنين، 3 أبريل 2023 في 10:51 م تمت كتابة ما يلي بواسطة ‪Mohammad Omar
S‬‏ ***@***.***‬‏>:‬

**Comment by yousifk95** [comment]
it wokrs ! big thanks 😘

‫في الاثنين، 3 أبريل 2023 في 11:28 م تمت كتابة ما يلي بواسطة يوسف كامل <‪
***@***.***‬‏>:‬
