### ISSUE TITLE
'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by pablogameing4000** [Deviper-Labs/Web-Proxy-PHP-Colab#2]
When running the final block of code, this error keeps popping up

```
AttributeError                            Traceback (most recent call last)
[<ipython-input-8-68c48a12c66a>](https://localhost:8080/#) in <cell line: 27>()
     25 # Regex to find URL
     26 
---> 27 url = re.search("tcp.*$", data).group()
     28 
     29 # Turn tcp to http

AttributeError: 'NoneType' object has no attribute 'group'
```

I saw something in another issue report about the URL being stored in a file, but I couldn't find anything while looking through the explorer.

**Comment by Deviper-Labs** [comment]
Hey there,
The `NoneType` error occurs when the regex search fails to find the ngrok url for whatever reason, in this case it was because ngrok needed to be updated to use the latest version. Also, the url is normally found in `php-proxy-app/ngrok.log`. Should be fixed now.
